[package]
name = "anycut-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
uiautomation = { version = "0.25", features = ["pattern"] }
windows = { version = "0.62.2", features = ["Win32_Foundation"] }
